apiVersion: v1
kind: Pod
metadata:
  name: multi-container
spec:
  volumes:
    - name: shared-data
      emptyDir:
        {}
  containers:
    # 1st Container Section

    - name: web-container
      image: nginx
      volumeMounts:
      - name: shared-data
        mountPath: /usr/share/nginx/html

    # 2nd Container Section
    - name: ftp-container
      image: fauria/vsftpd
      volumeMounts:
        - mountPath: /pod-data
          name: shared-data