apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myGolangApp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: myGolangApp

  # Template is for Pod Specifications    

  template:
    metadata:
      labels:
        app: myGolangApp
    spec:
      containers:
        - name: myapp
          image: gcr.io/playground-s-11-82a90540/myapp:blue
          ports:
            - containerPort: 8888 

